export const Users = [
  {
    id: 1,
    profilePicture: 'person/1.jpg',
    username: 'Dave',
  },
  {
    id: 2,
    profilePicture: 'person/3.jpg',
    username: 'Sonny',
  },
  {
    id: 3,
    profilePicture: 'person/4.jpg',
    username: 'Odoi',
  },
  {
    id: 4,
    profilePicture: 'person/5.jpg',
    username: 'Willock',
  },
  {
    id: 5,
    profilePicture: 'person/6.jpg',
    username: 'Bruno',
  },
  {
    id: 6,
    profilePicture: 'person/7.jpg',
    username: 'Mary',
  },
  {
    id: 7,
    profilePicture: 'person/8.jpg',
    username: 'Lucy',
  },
  // {
  //   id: 8,
  //   profilePicture: 'person/main.jpg',
  //   username: 'Chuks',
  // },
  {
    id: 9,
    profilePicture: 'person/9.jpg',
    username: 'Tonia',
  },
  {
    id: 10,
    profilePicture: 'person/11.jpg',
    username: 'Danny',
  },
];

export const Posts = [
  {
    id: 1,
    desc: 'Hello everybody. Today is a beautiful day!.',
    photo: 'posts/1.jpeg',
    date: '5 mins ago',
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: 'posts/2.jpg',
    date: '15 mins ago',
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: 'Every moment is a fresh beginning.',
    photo: 'posts/3.jpg',
    date: '1 hour ago',
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: 'posts/5.jpg',
    date: '4 hours ago',
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: 'posts/6.jpg',
    date: '5 hours ago',
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: 'posts/7.jpg',
    date: '1 day ago',
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: 'Never regret anything that made you smile.',
    photo: 'posts/8.jpg',
    date: '2 days ago',
    userId: 7,
    like: 52,
    comment: 3,
  },
  // {
  //   id: 8,
  //   photo: 'posts/10.jpeg',
  //   date: '3 days ago',
  //   userId: 8,
  //   like: 15,
  //   comment: 1,
  // },
  {
    id: 9,
    desc: 'Change the world by being yourself.',
    photo: 'posts/11.jpeg',
    date: '5 days ago',
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: 'posts/12.jpeg',
    date: '1 week ago',
    userId: 10,
    like: 104,
    comment: 12,
  },
];
